# Generated by Django 4.0.1 on 2022-02-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_bio_alter_tag_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to='users.Profile', verbose_name='Blocked Users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, to='users.Profile', verbose_name='Matches'),
        ),
    ]
