# Generated by Django 4.0.1 on 2022-02-23 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_blockrequest_alter_profile_blocked_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL, verbose_name='Auth User'),
        ),
    ]
