# Generated by Django 4.0.1 on 2022-02-23 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockrequest',
            name='block_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_receiver', to='users.profile'),
        ),
        migrations.AddField(
            model_name='blockrequest',
            name='block_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_sender', to='users.profile'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='match_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_receiver', to='users.profile'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='match_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_sender', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='matches', to='users.Profile', verbose_name='Blocked Users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='blocked_users', to='users.Profile', verbose_name='Matches'),
        ),
        migrations.AddConstraint(
            model_name='blockrequest',
            constraint=models.UniqueConstraint(fields=('block_sender', 'block_receiver'), name='Blocked'),
        ),
        migrations.AddConstraint(
            model_name='matchrequest',
            constraint=models.UniqueConstraint(fields=('match_sender', 'match_receiver'), name='Match'),
        ),
    ]
