# Generated by Django 4.0.1 on 2022-02-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_blockrequest_block_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to='users.Profile', verbose_name='Blocked Users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, to='users.Profile', verbose_name='Matches'),
        ),
    ]
