# Generated by Django 4.0.1 on 2022-02-23 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_blocked_users_alter_profile_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Auth User'),
        ),
    ]
