# Generated by Django 4.0.1 on 2022-03-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_tag_name_alter_tag_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
