# Generated by Django 4.0.1 on 2022-03-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_like_comment_alter_like_post'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='Profile Liked By',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='Comment Liked By',
        ),
    ]
