# Generated by Django 4.0.1 on 2022-03-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_listing_address_listing_image_listing_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='listing',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.profile', verbose_name='Profile Address'),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='listing',
            name='street1',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Street 1'),
        ),
        migrations.AddField(
            model_name='listing',
            name='street2',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Street 2'),
        ),
        migrations.AddField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(default='My apartment', max_length=100),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
