# Generated by Django 4.0.1 on 2022-03-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_address_profile_delete_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='users.profile', verbose_name='Profile Address'),
        ),
    ]
