# Generated by Django 4.0.1 on 2022-03-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_listing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Open'),
        ),
    ]
