# Generated by Django 3.2 on 2022-04-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_profile_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(blank=True, default='email', max_length=255, null=True),
        ),
    ]
