# Generated by Django 3.2 on 2022-04-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
