# Generated by Django 3.2 on 2022-04-16 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'Like'), ('C', 'Comment'), ('P', 'Post')], default='L', max_length=1)),
                ('message', models.CharField(default='You have a new notification', max_length=100)),
                ('for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_for', to='users.profile')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_from', to='users.profile')),
            ],
        ),
    ]
