# Generated by Django 4.0.3 on 2022-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20220416_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, to='users.profile', verbose_name='Matches'),
        ),
    ]
