# Generated by Django 4.0.3 on 2022-04-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_profile_matches'),
        ('users', '0042_alter_profile_matches'),
    ]

    operations = [
    ]
