# Generated by Django 3.2 on 2022-04-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_merge_20220424_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='_users_profile_matches_+', to='users.Profile', verbose_name='Matches'),
        ),
    ]
