# Generated by Django 3.2 on 2022-04-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_profile_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
