# Generated by Django 3.2 on 2022-04-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_notification_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('C', 'Comment'), ('P', 'Post')], default='L', max_length=1),
        ),
    ]
