# Generated by Django 3.2 on 2022-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('C', 'Comment'), ('P', 'Post'), ('CR', 'Connection Request'), ('CRA', 'Connection Request Accepted')], default='P', max_length=3),
        ),
    ]
