# Generated by Django 4.0.3 on 2022-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_notification_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, to='users.profile', verbose_name='Matches'),
        ),
    ]
