# Generated by Django 3.2 on 2022-04-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_profile_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, default='You have a new notification', max_length=100, null=True),
        ),
    ]
